// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/migrations usam conexão direta (session mode) — a app em runtime usa
    // DATABASE_URL (pooled) separadamente, ver src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
